-- P2-E: Add customer_email column to payments for optional receipt delivery
ALTER TABLE payments ADD COLUMN IF NOT EXISTS customer_email TEXT;

-- Customer receipt email template
INSERT INTO email_templates (type, name, subject, body_html, body_text, variables)
VALUES (
  'customer_receipt',
  'Customer Payment Receipt',
  'Your payment receipt — {{amount}} {{currency}}',
  E'<!DOCTYPE html>\n<html>\n<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head>\n<body style="margin:0;padding:0;background:#09090b;font-family:-apple-system,BlinkMacSystemFont,''Segoe UI'',Roboto,sans-serif">\n<div style="max-width:480px;margin:0 auto;padding:40px 20px">\n  <div style="background:#18181b;border:1px solid #27272a;border-radius:16px;padding:32px;text-align:center">\n    <div style="margin-bottom:24px">\n      <span style="display:inline-block;background:linear-gradient(135deg,#2563EB,#7C3AED);-webkit-background-clip:text;-webkit-text-fill-color:transparent;font-size:20px;font-weight:700">⚡ goBlink</span>\n    </div>\n    <div style="background:#10b98120;border:1px solid #10b98140;border-radius:12px;padding:12px;margin-bottom:24px">\n      <span style="color:#10b981;font-size:14px;font-weight:600">✓ Payment Confirmed</span>\n    </div>\n    <p style="color:#f4f4f5;font-size:28px;font-weight:700;margin:0 0 4px">{{amount}} {{currency}}</p>\n    <p style="color:#71717a;font-size:13px;margin:0 0 24px">{{date}}</p>\n    <div style="border-top:1px solid #27272a;padding-top:20px;text-align:left">\n      <table style="width:100%;border-collapse:collapse">\n        <tr><td style="color:#a1a1aa;font-size:13px;padding:6px 0">Merchant</td><td style="color:#e4e4e7;font-size:13px;padding:6px 0;text-align:right">{{merchant_name}}</td></tr>\n        <tr><td style="color:#a1a1aa;font-size:13px;padding:6px 0">Order ID</td><td style="color:#e4e4e7;font-size:13px;padding:6px 0;text-align:right;font-family:monospace">{{order_id}}</td></tr>\n        <tr><td style="color:#a1a1aa;font-size:13px;padding:6px 0">Network</td><td style="color:#e4e4e7;font-size:13px;padding:6px 0;text-align:right;text-transform:capitalize">{{chain}}</td></tr>\n        <tr><td style="color:#a1a1aa;font-size:13px;padding:6px 0">Transaction</td><td style="padding:6px 0;text-align:right"><a href="{{explorer_url}}" style="color:#60a5fa;font-size:13px;font-family:monospace;text-decoration:none">{{tx_hash_short}}</a></td></tr>\n      </table>\n    </div>\n    <div style="margin-top:24px;padding-top:20px;border-top:1px solid #27272a">\n      <a href="{{receipt_url}}" style="display:inline-block;background:linear-gradient(135deg,#2563EB,#7C3AED);color:#fff;font-size:14px;font-weight:600;padding:10px 24px;border-radius:10px;text-decoration:none">View Full Receipt</a>\n    </div>\n  </div>\n  <p style="color:#52525b;font-size:11px;text-align:center;margin-top:16px">Powered by goBlink · Secure crypto payments</p>\n</div>\n</body>\n</html>',
  E'Payment Receipt\n\nYour payment of {{amount}} {{currency}} to {{merchant_name}} has been confirmed.\n\nOrder ID: {{order_id}}\nNetwork: {{chain}}\nTransaction: {{explorer_url}}\nDate: {{date}}\n\nView receipt: {{receipt_url}}\n\nPowered by goBlink',
  '[{"name": "amount", "description": "Payment amount"}, {"name": "currency", "description": "Payment currency"}, {"name": "merchant_name", "description": "Merchant business name"}, {"name": "order_id", "description": "Order ID"}, {"name": "chain", "description": "Blockchain network"}, {"name": "explorer_url", "description": "Block explorer transaction URL"}, {"name": "tx_hash_short", "description": "Truncated transaction hash"}, {"name": "date", "description": "Confirmation date"}, {"name": "receipt_url", "description": "URL to view the full receipt"}]'
)
ON CONFLICT (type) DO NOTHING;
